# 搜索关键词
keyWords: 

# 最低评论数
lowCommentNum: 1
# 最低值率
lowWorthyNum: 70
# 满意商品数量
satisfyNum: 10
# 过滤词
filterWords: 
- "过期"
- "售罄"

# 定时任务多长执行一次 单位秒 默认 3个小时
tickTime: 60
# 钉钉token
dingdingToken: "9e4044952fe5c599afed3815ccaa387c650fd07bda96512648acfceb1b202ada"

# 签到时间(默认早上8:30)
cron: "0 10 10 ? * *"
